### ISSUE TITLE
Unable to Select options from the drop down when the textfield is in the tableview cell

### ISSUE THREAD

**Issue by KhadijaDaruwala** [jriosdev/iOSDropDown#37]
I have a tableview in which one of the cell consists of the textfield. On click of the textfield the drop down appears but i am not able to select any option from the drop.. Seems like its not responding
![screenshot 2019-02-26 at 5 11 17 pm](https://user-images.githubusercontent.com/16515273/53410343-9450d780-39e9-11e9-8c1b-e9aa8bde945b.png)

**Comment by El-Diablo1** [comment]
> I have a tableview in which one of the cell consists of the textfield. On click of the textfield the drop down appears but i am not able to select any option from the drop.. Seems like its not responding
> ![screenshot 2019-02-26 at 5 11 17 pm](https://user-images.githubusercontent.com/16515273/53410343-9450d780-39e9-11e9-8c1b-e9aa8bde945b.png)

got any solution about this?

**Comment by kalpacse96** [comment]
I too have the same problem !! Any solutions  to this.

**Comment by ibru** [comment]
Hi guys, I've recently successfully used this lib in my collection view cells.
I cannot prepare pull request since I've changed bunch of stuff in the class to adapt it to my needs, but at lest hare is my findings.
I believe the source of the problem you have is because the class adds the options table as subview of self.superview, which in your case is the table view cell. This happens in `func showList()`. But the options table is bigger then your cell so it might get clipped (as it was happening in my case with UICollectionView) or maybe its fully visible but not working properly. 
What I've done is I made a new property that allows to provide different view to which the table will be added to as a subview. And I provide UICollectionView instance as this view. With this approach it works correctly. But it also requires provide custom positioning because the class internally positions the options table relative to drop down frame but you need to position it relative to whole table/collection view.
Hope this helps you a bit.

**Comment by jriosdev** [comment]
Issue solved Please update your code
Thanks

**Comment by hiteshborse12** [comment]
> I have a tableview in which one of the cell consists of the textfield. On click of the textfield the drop down appears but i am not able to select any option from the drop.. Seems like its not responding
> ![screenshot 2019-02-26 at 5 11 17 pm](https://user-images.githubusercontent.com/16515273/53410343-9450d780-39e9-11e9-8c1b-e9aa8bde945b.png)

you can add hitTest(_:with:) method. https://developer.apple.com/documentation/uikit/uiview/1622469-hittest
